package com.yungnickyoung.minecraft.yungsroads.world.structureregion;

import com.yungnickyoung.minecraft.yungsroads.YungsRoadsCommon;
import com.yungnickyoung.minecraft.yungsroads.world.config.RoadSetting;
import com.yungnickyoung.minecraft.yungsroads.world.road.Road;
import com.yungnickyoung.minecraft.yungsroads.world.road.RoadCenter;
import com.yungnickyoung.minecraft.yungsroads.world.road.generator.LatticePathfinder;
import it.unimi.dsi.fastutil.longs.LongArrayList;
import it.unimi.dsi.fastutil.longs.LongList;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtIo;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.ChunkPos;

import javax.annotation.Nullable;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Caches StructureRegions for a given world and exposes methods for retrieving them.
 * If a StructureRegion is not yet cached, generation is deferred to {@link StructureRegionGenerator}.
 * Thread-safe.
 */
public class StructureRegionCache {
    private final Path savePath;
    private final StructureRegionGenerator structureRegionGenerator;

    /**
     * Cache of StructureRegions, keyed by region key.
     * Holds futures so that a region being generated by one thread can be awaited by others, without
     * blocking unrelated regions.
     */
    private final ConcurrentHashMap<Long, CompletableFuture<StructureRegion>> cache = new ConcurrentHashMap<>();

    public StructureRegionCache(ServerLevel level, Path dimensionPath) {
        this.structureRegionGenerator = new StructureRegionGenerator(level);
        this.savePath = dimensionPath.resolve("roads").toAbsolutePath();
        createDirectoryIfDoesNotExist();
    }

    /**
     * Gets the {@link StructureRegion} with the given key, loading or generating it if needed.
     * <p>
     * If a corresponding structure region file exists, we load the data from it.
     * If the file does not exist, is corrupt, or is from an older format version,
     * generation is deferred to {@link StructureRegionGenerator#generateRegion}.
     */
    public StructureRegion getRegion(long regionKey) {
        CompletableFuture<StructureRegion> future = new CompletableFuture<>();
        CompletableFuture<StructureRegion> existing = this.cache.putIfAbsent(regionKey, future);
        if (existing != null) {
            return existing.join();
        }

        // This thread claimed the region, so it loads or generates it. Other threads requesting it wait on the future.
        try {
            StructureRegion structureRegion = loadOrGenerateRegion(regionKey);
            future.complete(structureRegion);
            return structureRegion;
        } catch (Throwable t) {
            this.cache.remove(regionKey, future);
            future.completeExceptionally(t);
            throw t;
        }
    }

    public StructureRegion getRegion(StructureRegionPos regionPos) {
        return this.getRegion(regionPos.asLong());
    }

    /**
     * Returns the region with the given key if it's already loaded, without loading or generating it.
     */
    @Nullable
    public StructureRegion getRegionIfLoaded(long regionKey) {
        CompletableFuture<StructureRegion> future = this.cache.get(regionKey);
        return future != null && future.isDone() && !future.isCompletedExceptionally() ? future.join() : null;
    }

    /**
     * Returns every region whose roads may pass within {@link StructureRegion#INDEX_PADDING} blocks of the chunk,
     * in a deterministic order. Since roads may cross region borders, this can include neighboring regions.
     */
    public List<StructureRegion> getRegionsNearChunk(ChunkPos chunkPos) {
        List<StructureRegion> regions = new ArrayList<>();
        for (long regionKey : regionKeysNearChunk(chunkPos)) {
            regions.add(getRegion(regionKey));
        }
        return regions;
    }

    /**
     * Returns the road center positions from all regions that are within {@link StructureRegion#INDEX_PADDING}
     * blocks of the chunk, in a deterministic order.
     */
    public List<RoadCenter> getRoadCentersNearChunk(ChunkPos chunkPos) {
        List<RoadCenter> centers = new ArrayList<>();
        for (StructureRegion region : getRegionsNearChunk(chunkPos)) {
            centers.addAll(region.getRoadCentersNearChunk(chunkPos.toLong()));
        }
        return centers;
    }

    /**
     * Whether any road center position is within the given horizontal range of the position.
     * The range must not exceed {@link StructureRegion#INDEX_PADDING}.
     */
    public boolean hasRoadNear(BlockPos pos, int range) {
        for (RoadCenter center : getRoadCentersNearChunk(new ChunkPos(pos))) {
            int dx = center.pos().getX() - pos.getX();
            int dz = center.pos().getZ() - pos.getZ();
            if (dx * dx + dz * dz <= range * range) {
                return true;
            }
        }
        return false;
    }

    /**
     * Finds the road node whose jittered position is at the given x-z position, searching only regions that are
     * already loaded. Intended for debug displays, which shouldn't trigger region generation.
     */
    @Nullable
    public Road.DebugNode findLoadedDebugNodeAt(BlockPos pos) {
        for (long regionKey : regionKeysNearChunk(new ChunkPos(pos))) {
            StructureRegion region = getRegionIfLoaded(regionKey);
            if (region == null) {
                continue;
            }
            for (Road road : region.getRoads()) {
                for (Road.DebugNode node : road.nodes) {
                    if (node.jitteredPos.getX() == pos.getX() && node.jitteredPos.getZ() == pos.getZ()) {
                        return node;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Returns every region that has finished loading or generating, in no particular order.
     */
    public List<StructureRegion> getLoadedRegions() {
        List<StructureRegion> regions = new ArrayList<>();
        for (Map.Entry<Long, CompletableFuture<StructureRegion>> entry : this.cache.entrySet()) {
            StructureRegion region = getRegionIfLoaded(entry.getKey());
            if (region != null) {
                regions.add(region);
            }
        }
        return regions;
    }

    /**
     * Replaces a region in the cache and on disk, such as after regenerating it with different settings.
     * Chunks that were already placed using the old region aren't changed.
     */
    public void replaceRegion(StructureRegion region) {
        long regionKey = region.getPos().asLong();
        this.cache.put(regionKey, CompletableFuture.completedFuture(region));
        writeStructureRegionFile(region, this.savePath.resolve(region.getFileName()));
    }

    /**
     * Removes a region from the cache and from disk, so it's generated again the next time it's needed.
     */
    public void invalidateRegion(long regionKey) {
        this.cache.remove(regionKey);
        try {
            Files.deleteIfExists(this.savePath.resolve(new StructureRegionPos(regionKey).getFileName()));
        } catch (IOException e) {
            YungsRoadsCommon.LOGGER.error("Unable to delete structure region file for region {}", new StructureRegionPos(regionKey), e);
        }
    }

    public StructureRegionGenerator getStructureRegionGenerator() {
        return structureRegionGenerator;
    }

    /**
     * Returns the key of each region that could own a road reaching the chunk, in a deterministic order.
     */
    public static LongList regionKeysNearChunk(ChunkPos chunkPos) {
        return regionKeysNearArea(chunkPos.getMinBlockX(), chunkPos.getMinBlockZ(), chunkPos.getMaxBlockX(), chunkPos.getMaxBlockZ());
    }

    /**
     * Returns the key of each region that could own a road reaching the given block area, in a deterministic order.
     * A road stays within {@link #maxRoadReach} blocks of its owning region, so only regions that close are included.
     */
    public static LongList regionKeysNearArea(int minX, int minZ, int maxX, int maxZ) {
        int reach = maxRoadReach();
        int minRegionX = (minX - reach) >> StructureRegionPos.REGION_SIZE_SHIFT;
        int maxRegionX = (maxX + reach) >> StructureRegionPos.REGION_SIZE_SHIFT;
        int minRegionZ = (minZ - reach) >> StructureRegionPos.REGION_SIZE_SHIFT;
        int maxRegionZ = (maxZ + reach) >> StructureRegionPos.REGION_SIZE_SHIFT;

        LongList regionKeys = new LongArrayList();
        for (int regionX = minRegionX; regionX <= maxRegionX; regionX++) {
            for (int regionZ = minRegionZ; regionZ <= maxRegionZ; regionZ++) {
                regionKeys.add(StructureRegionPos.asLong(regionX, regionZ));
            }
        }
        return regionKeys;
    }

    /**
     * The furthest a road's indexed positions can extend outside the region that owns it, in blocks.
     * Roads start inside their owning region, and stay within the search margin of their endpoints' bounding box,
     * plus jitter and index padding. Each road type has its own jitter, so the most any type could have is assumed.
     */
    private static int maxRoadReach() {
        int step = YungsRoadsCommon.CONFIG.advanced.nodeStepDistance;
        return StructureRegionGenerator.MAX_ROAD_LENGTH
                + LatticePathfinder.maxSearchMargin(StructureRegionGenerator.MAX_ROAD_LENGTH, step)
                + (int) Math.ceil(RoadSetting.JITTER_AMOUNT.max())
                + StructureRegion.INDEX_PADDING;
    }

    private StructureRegion loadOrGenerateRegion(long regionKey) {
        StructureRegionPos structureRegionPos = new StructureRegionPos(regionKey);

        Path file = this.savePath.resolve(structureRegionPos.getFileName());
        if (Files.exists(file)) {
            try {
                CompoundTag structureRegionNbt = NbtIo.read(file);
                if (structureRegionNbt != null) {
                    return StructureRegion.fromNbt(regionKey, structureRegionNbt, this.structureRegionGenerator.getRoadTypes());
                }
            } catch (IOException | RuntimeException e) {
                YungsRoadsCommon.LOGGER.warn("Unable to load roads file {}. Regenerating structure region from scratch. Reason: {}", file, e.toString());
            }
        }

        long startTime = System.nanoTime();
        StructureRegion structureRegion = this.structureRegionGenerator.generateRegion(regionKey);
        YungsRoadsCommon.LOGGER.debug("Generated structure region {} with {} roads in {} ms",
                structureRegionPos, structureRegion.getRoads().size(), (System.nanoTime() - startTime) / 1_000_000);
        writeStructureRegionFile(structureRegion, file);
        return structureRegion;
    }

    private void writeStructureRegionFile(StructureRegion structureRegion, Path file) {
        try {
            NbtIo.write(structureRegion.toNbt(), file);
        } catch (IOException e) {
            YungsRoadsCommon.LOGGER.error("Unable to write structure region file {}", file);
            YungsRoadsCommon.LOGGER.error(e);
        }
    }

    private void createDirectoryIfDoesNotExist() {
        try {
            Files.createDirectories(this.savePath);
        } catch (IOException e) {
            YungsRoadsCommon.LOGGER.error("Unable to create roads save path {}", this.savePath);
            YungsRoadsCommon.LOGGER.error(e);
        }
    }
}
