modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Roads/issues"

[[mods]]
    modId="yungsroads"
    version="${file.jarVersion}"
	displayName="YUNG's Roads"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG"
    description="Adds naturally generated roads connecting structures throughout the world!"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-roads"

[[dependencies.yungsroads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.yungsroads]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.8,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.yungsroads]]
    modId="yungsapi"
    versionRange="[1.18.2-Forge-2.0.7,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
