modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Roads/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
credits="${modCredits}"
authors="${modAuthor}"
description="${modDescription}"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-roads"

[[dependencies.yungsroads]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="SERVER"

[[dependencies.yungsroads]]
modId="yungsapi"
versionRange="[1.16.4-Forge-13,)"
mandatory=true
ordering="NONE"
side="BOTH"